# Generated by Django 3.2 on 2021-07-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products/pics')),
                ('product_name', models.CharField(max_length=20, unique=True)),
                ('product_type', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=500)),
                ('product_selling_price', models.IntegerField()),
                ('product_orginal_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
